(comment "filename: redbridge_datamapper.clj")
(import '(org.jruby.embed ScriptingContainer PathType))
(def c (ScriptingContainer.))
(def path (str "ENV['GEM_PATH']=" "'" (System/getProperty "user.dir") "/clojure/lib/jruby/1.8" "'"))
(. c runScriptlet path)
(. c runScriptlet "require 'rubygems'; require 'dm-core'; require 'dm-migrations'")
(. c runScriptlet "DataMapper.setup(:default, 'sqlite::memory:')")
(. c runScriptlet PathType/CLASSPATH "category_def.rb")
(. c runScriptlet PathType/CLASSPATH "categories.rb")
(. c runScriptlet "p Category.all")
